cant reach the container from another job

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -34,10 +34,10 @@ jobs:
     - name: Start docker compose services
       run: docker compose up -d && sleep 5
 
-    - name: Show docker compose logs
+    - name: Show docker compose logs after creating services
       run: docker compose logs --no-color --timestamps || true
 
-    - name: Run setup
+    - name: Run setup databases in the couchdb inside the container
       run: npm run setup
       env:
         SOURCE_URL: ${{ secrets.SOURCE_URL }}
@@ -49,31 +49,20 @@ jobs:
         SOURCE_URL: ${{ secrets.SOURCE_URL }}
         DEBUG: 'none'
 
-    - name: Show docker compose logs
+    - name: Show docker compose logs after running tests
       if: success() || failure()
       run: docker compose logs --no-color --timestamps | grep -v "couchdb" || true
 
-  integration-tests:
-    runs-on: ubuntu-latest
-    needs: [deploy]
-    steps:
-    - uses: actions/checkout@v6
-    - name: Use Node.js ${{ matrix.node-version }}
-      uses: actions/setup-node@v6
-      with:
-        node-version: ${{ matrix.node-version }}
-        cache: 'npm'
-    - run: npm ci
     - name: Create local config for tests to use the couchdb outside the container
       run: |
         echo 'module.exports = { usersDbConnection: { url: "http://localhost:5984" }};' > config/localhost.js
-    - name: Run Integration tests
-      run: DEBUG=replay* npm run coverage || echo 'Test run failed replay no longer is working with latest nano which uses node fetch'
-    - name: Run integration tests using the app with local couchdb
+
+    - name: Run integration tests using the app against the couchdb in the contianer
       run: npm run test:deprecated:coverage
       env:
         SOURCE_URL: ${{ secrets.SOURCE_URL }}
         DEBUG: 'test:deprecated'
+
     - name: Upload coverage report
       uses: actions/upload-artifact@v5
       if: success() || failure()
@@ -86,6 +75,20 @@ jobs:
       uses: coverallsapp/github-action@master
       with:
         github-token: ${{ secrets.GITHUB_TOKEN }}
+
+  integration-tests:
+    runs-on: ubuntu-latest
+    needs: [deploy]
+    steps:
+    - uses: actions/checkout@v6
+    - name: Use Node.js ${{ matrix.node-version }}
+      uses: actions/setup-node@v6
+      with:
+        node-version: ${{ matrix.node-version }}
+        cache: 'npm'
+    - run: npm ci
+    - name: Run Integration tests
+      run: DEBUG=replay* npm run coverage || echo 'Test run failed replay no longer is working with latest nano which uses node fetch'
 
   ui-tests:
     runs-on: ubuntu-latest
